### ISSUE TITLE
Add base hostname to cluster_infos.json

### ISSUE THREAD

**Issue by tsebastiani** [crc-org/snc#645]
Would be helpful to have also the base domain (xxx.xxx.xxx.xxx.nip.io) in the output json.

**Comment by gbraad** [comment]
Aren't we already doing this?

https://github.com/crc-org/snc/blob/791d8e2cda8042c7fa0ff81187aab6df3b1f46d7/crc-bundle-info.json.sample#L34

**Comment by tsebastiani** [comment]
I'm not sure if we're talking about the same thing, but the crc-cloud script, when the instance is created, produces an output file in the working directory, in the machine that launched the script, containing the console address and the api address 
```
{
  "api": {
    "address": "https://api.18.236.123.92.nip.io",
    "port": "6443"
  },
  "console": {
    "address": "https://console-openshift-console.apps.18.236.123.92.nip.io",
    "port": "443"
  }
}
```
the purpose of this script is to pass these infos to the next steps of the automation in which it might be included (like CI/CD) pipelines, I noticed that it might be helpful to have the base address as well.

**Comment by gbraad** [comment]
they are included in the bundles we deliver, so this might the result of another step that you aren't performing... and perhaps need to be seperated from the final bundling.

**Comment by praveenkumar** [comment]
@tsebastiani We build `api` and `console` address using the `api.<cluster_name>.<baseDomain>` and `console-<namespace>.apps-<cluster_name>.<baseDomain>` and in the cloud-script it changes because we add additional domain for `nip.io` and also patch the console domain to consume `nip.io` . I think SNC side we don't need to add those details since it is already correct for crc context.

**Comment by tsebastiani** [comment]
the problem is that now, in my github action, so from outside the VM, in order to have the base hostname , I've to do something like that
```
BASE_HOST=`$JQ -r '.api.address'  $CLUSTER_INFO_PATH | sed -r 's#https:\/\/api\.(.+\.nip\.io)#\1#'`
```
That's not the most comfortable thing, having it as a property in cluster_infos.json is one line of code and wouldn't bother too much IMHO

**Comment by cfergeau** [comment]
If you are talking about `cluster_infos.json`, it's a file generated by crc-cloud https://github.com/crc-org/crc-cloud/blob/6869ce2ee817066b3cc02836f0323d3e1893360a/crc-cloud.sh#L175-L183 so I would move this issue/the discussion to crc-cloud.
snc generates a `crc-bundle-info.json` file with this kind of content: https://github.com/crc-org/snc/blob/master/crc-bundle-info.json.sample

Since it's crc-cloud doing the `.nip.io` patching, I agree with Praveen that it's up to crc-cloud to do any patching/provide any additional info which might be missing.

**Comment by tsebastiani** [comment]
> If you are talking about `cluster_infos.json`, it's a file generated by crc-cloud https://github.com/crc-org/crc-cloud/blob/6869ce2ee817066b3cc02836f0323d3e1893360a/crc-cloud.sh#L175-L183 so I would move this issue/the discussion to crc-cloud. snc generates a `crc-bundle-info.json` file with this kind of content: https://github.com/crc-org/snc/blob/master/crc-bundle-info.json.sample
> 
> Since it's crc-cloud doing the `.nip.io` patching, I agree with Praveen that it's up to crc-cloud to do any patching/provide any additional info which might be missing.

If you are talking about cluster_infos.json, it's a file generated by crc-cloud https://github.com/crc-org/crc-cloud/blob/6869ce2ee817066b3cc02836f0323d3e1893360a/crc-cloud.sh#L175-L183 so I would move this issue/the discussion to crc-cloud.
snc generates a crc-bundle-info.json file with this kind of content: https://github.com/crc-org/snc/blob/master/crc-bundle-info.json.sample

Since it's crc-cloud doing the .nip.io patching, I agree with Praveen that it's up to crc-cloud to do any patching/provide any additional info which might be missing.

You're perfectly right, just figured out was in the wrong place, that was the root cause of the misunderstanding, I was following the notifications and didn't see that was placed in the wrong repo 😅, sorry about that
